### ISSUE TITLE
When compiling with TELEMETRY_MAVLINK plus DEBUG,CLI,USB_SERIAL, DEBUG/USB SERIAL should IMHO take precedence

### ISSUE THREAD

**Issue by rotorman** [olliw42/mTX#2]
I am trying to perform internal debug statistics and trying to build with TELEMETRY_MAVLINK plus DEBUG and CLI. Latter two automatically set USB_SERIAL:
https://github.com/olliw42/opentx/blob/875a4e98ec069cc0f42ed0d6a2c7b3df149b1342/radio/src/targets/common/arm/stm32/CMakeLists.txt#L45-L55

Currently, building fails, when TELEMETRY_MAVLINK, DEBUG and CLI are selected simultaneously. Would appreciate, if you could please look into it.

IMHO CLI or DEBUG should take precedence over USB when included and TELEMETRY_MAVLINK should "release" the top USB-port in order to be able also debug mavlinkTask. Thus if either DEBUG or CLI is selected, then mavlinkTask should not claim USB port. That USB-C MAVLink router functionality cannot be debugged this way, is clear to me.

Thank you!

**Comment by olliw42** [comment]
I once did a try with cli with some conditions I can't remember, but I had RAM issues with cli ... 
so this might be an issue to look for in addition

it would be interesting to get this compiling and working with debug, or cli, or both but I'm afraid to say that I'm too stretched out currently to look at it.

I leave it open in case someone may want to pick up.

**Comment by olliw42** [comment]
I believe it's even better now, one can choose
so, since settled now, I'm closing
many thx !!
