### ISSUE TITLE
mavlinkTask stack size not 8-byte aligned

### ISSUE THREAD

**Issue by rotorman** [olliw42/mTX#3]
In RCGroups we previously discussed this:
https://github.com/olliw42/opentx/blob/875a4e98ec069cc0f42ed0d6a2c7b3df149b1342/radio/src/tasks.h#L55

I just now stumbled upon a further hint why the stack size needs to be a multiple of 8 bytes:
https://github.com/olliw42/opentx/blob/875a4e98ec069cc0f42ed0d6a2c7b3df149b1342/radio/src/rtos.h#L274

Please also see here, section 5:
[https://community.arm.com/developer/ip-products/processors/b/processors-ip-blog/posts/how-much-stack-memory-do-i-need-for-my-arm-cortex--m-applications](https://community.arm.com/developer/ip-products/processors/b/processors-ip-blog/posts/how-much-stack-memory-do-i-need-for-my-arm-cortex--m-applications)

I quote the interesting passage:
`... Maximum stack size required by the application thread (obtained from the stack usage report from compilation tools), and rounded up to multiple of eight (double word alignment).`

Would you please reconsider changing the value to something dividable by 8 (my suggestion was 512, but if 400 double words is enough, then this might also be a nice value to go with, similar to audioTask and mixerTask).

I would like to make some statistics about tasks, stack usage & so on, for this please see also #1 and #2 
After this is running, it will be possible to extract the required minimum value for the mavlinkTask.

**Comment by olliw42** [comment]
had responded to that in the rcgroups thread
IMHO not a concern
align is not size, you can align a single byte to 8 byte boundaries, and concerning stack that size is not divisible by 8 just means that we lose one entry we might still have
don't make it an elephant

what I rather think is that one should analyze what the stack need actually is, and once that is known to go from there ... the above value I just pulled out of my hair, so it's pointless to make small changes to it ... i.e., I argue one should first get the facts before wasting time. It seems that this is what you want to do, which is great, so let's wait for the result.
