### ISSUE TITLE
Indentation missing for try except blocks

### ISSUE THREAD

**Issue by rotorman** [olliw42/mTX#7]
@olliw42 I ran today your script again, and after your last changes, you removed indentation for try except blocks and this gets "IndentationError" for following lines:
https://github.com/olliw42/opentx/blob/99c68408840b18583fc35b1c9fb973951ab90479/radio/src/thirdparty/Mavlink/fmavgenerate_dialect.py#L52

https://github.com/olliw42/opentx/blob/99c68408840b18583fc35b1c9fb973951ab90479/radio/src/thirdparty/Mavlink/fmavgenerate_dialect.py#L54

https://github.com/olliw42/opentx/blob/99c68408840b18583fc35b1c9fb973951ab90479/radio/src/thirdparty/Mavlink/fmavgenerate_dialect.py#L61-L62

https://github.com/olliw42/opentx/blob/99c68408840b18583fc35b1c9fb973951ab90479/radio/src/thirdparty/Mavlink/fmavgenerate_dialect.py#L65-L67

Please consider adding 4 spaces in front of these lines. After adding 4 spaces in front of each of these lines, the script ran for me without errors.

**Comment by olliw42** [comment]
oh ... how the heck did that happen ... anyway: many thx for reporting !!
should be corrected now
closing
